function m3ha_compare_and_plot_across_IC (varargin)
%% Plot activation/inactivation and I-V curves across initial conditions
% Usage: m3ha_compare_and_plot_across_IC (varargin)
%
% Requires:
%       cd/m3ha_compute_and_plot_IT.m
%       cd/m3ha_compute_and_plot_Ih.m
%       cd/m3ha_compute_and_plot_IKir.m
%       cd/m3ha_compute_and_plot_IA.m
%       cd/m3ha_compute_and_plot_INaP.m
%
% File History:
% 2017-08-06 Created

%% Default parameters
outFolderDefault = pwd; % default output directory

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Plot curves for IT
[v, ~, ~, ~, ~, IMaxIT1, IInitIT1, IInfIT1] = ...
    m3ha_compute_and_plot_IT('Suffix', '_Destexhe_1998', 'Celsius', 33, ...
            'Cout', 2, 'Cin', 2.4e-4, 'Pcabar', 0.2e-3, ...
            'Shiftm', 1, 'Shifth', 1, 'Slopem', 1, 'Slopeh', 1);
[~, ~, ~, ~, ~, IMaxIT2, IInitIT2, IInfIT2] = ...
    m3ha_compute_and_plot_IT('Suffix', '_Destexhe_old', 'Celsius', 33, ...
            'Cout', 2, 'Cin', 2.4e-4, 'Pcabar', 0.2e-3, ...
            'Shiftm', 2, 'Shifth', 0, 'Slopem', 1, 'Slopeh', 1);
[~, ~, ~, ~, ~, IMaxIT3, IInitIT3, IInfIT3] = ...
    m3ha_compute_and_plot_IT('Suffix', '_Christine_soma', 'Celsius', 33, ...
            'Cout', 2, 'Cin', 2.4e-4, 'Pcabar', 3.98e-6, ....
            'Shiftm', -13.8, 'Shifth', -4.8, 'Slopem', 1.4, 'Slopeh', 1);
[~, ~, ~, ~, ~, IMaxIT4, IInitIT4, IInfIT4] = ...
    m3ha_compute_and_plot_IT('Suffix', '_Christine_dend', 'Celsius', 33, ...
            'Cout', 2, 'Cin', 2.4e-4, 'Pcabar', 3.98e-6, ....
            'Shiftm', -13.8, 'Shifth', -4.8, 'Slopem', 1.4, 'Slopeh', 1);
[~, ~, ~, ~, ~, IMaxIT5, IInitIT5, IInfIT5] = ...
    m3ha_compute_and_plot_IT('Suffix', '_SingleNeuronFitting5_soma', 'Celsius', 33, ...
            'Cout', 2, 'Cin', 2.4e-4, 'Pcabar', 2.8216e-7, ....
            'Shiftm', -13.8, 'Shifth', -4.8, 'Slopem', 1.4, 'Slopeh', 1);
[~, ~, ~, ~, ~, IMaxIT6, IInitIT6, IInfIT6] = ...
    m3ha_compute_and_plot_IT('Suffix', '_SingleNeuronFitting5_dend', 'Celsius', 33, ...
            'Cout', 2, 'Cin', 2.4e-4, 'Pcabar', 5.6634e-5, ....
            'Shiftm', -13.8, 'Shifth', -4.8, 'Slopem', 1.4, 'Slopeh', 1);

% Plot curves for Ih
[~, ~, ~, IMaxIh1, IInfIh1] = ...
    m3ha_compute_and_plot_Ih('Suffix', '_Destexhe_1998', 'Celsius', 33, ...
            'Ghbar', 2.2e-5, 'Erev', -43, 'Shiftm', 0);
[~, ~, ~, IMaxIh3, IInfIh3] = ...
    m3ha_compute_and_plot_Ih('Suffix', '_Christine', 'Celsius', 33, ...
            'Ghbar', 1.1e-5, 'Erev', -43, 'Shiftm', 11.4);
[~, ~, ~, IMaxIh5, IInfIh5] = ...
    m3ha_compute_and_plot_Ih('Suffix', '_SingleNeuronFitting5_soma', 'Celsius', 33, ...
            'Ghbar', 3.0206e-7, 'Erev', -43, 'Shiftm', 11.4);
[~, ~, ~, IMaxIh6, IInfIh6] = ...
    m3ha_compute_and_plot_Ih('Suffix', '_SingleNeuronFitting5_dend', 'Celsius', 33, ...
            'Ghbar', 1.0226e-6, 'Erev', -43, 'Shiftm', 11.4);

% Plot curves for IKir, IA and INaP
[~, ~,IMaxIKir, IInfIKir] = ...
    m3ha_compute_and_plot_IKir('Suffix', '_Destexhe_1998', 'Celsius', 33, ...
            'Gkbar', 2.0e-5, 'Ek', -100);
[~, ~, ~, ~, ~, ~, ~, IMaxIA, IInitIA, IInfIA] = ...
    m3ha_compute_and_plot_IA('Suffix', '_Destexhe_1998', 'Celsius', 33, ...
            'Gkbar', 5.5e-3, 'Ek', -100);
[~, ~, ~, ~, IMaxINaP, IInitINaP, IInfINaP] = ...
    m3ha_compute_and_plot_INaP('Suffix', '_Destexhe_1998', 'Celsius', 33, ...
            'Gnabar', 5.5e-6, 'ENa', 88);

% Plot summary I_V curves
m3ha_compute_and_plot_all_IV(pwd, '_Destexhe_1998', v, IInitIT1, IInfIT1, IInfIh1, ...
                IInfIKir, IInitIA, IInfIA, IInitINaP, IInfINaP);
m3ha_compute_and_plot_all_IV(pwd, '_Destexhe_old', v, IInitIT2, IInfIT2, IInfIh1, ...
                IInfIKir, IInitIA, IInfIA, IInitINaP, IInfINaP);
m3ha_compute_and_plot_all_IV(pwd, '_Christine_soma', v, IInitIT3, IInfIT3, IInfIh3, ...
                IInfIKir, IInitIA, IInfIA, IInitINaP, IInfINaP);
m3ha_compute_and_plot_all_IV(pwd, '_Christine_dend', v, IInitIT4, IInfIT4, IInfIh3, ...
                IInfIKir, IInitIA, IInfIA, IInitINaP, IInfINaP);
m3ha_compute_and_plot_all_IV(pwd, '_SingleNeuronFitting5_soma', v, ...
                IInitIT5, IInfIT5, IInfIh5, ...
                IInfIKir, IInitIA, IInfIA, IInitINaP, IInfINaP);
m3ha_compute_and_plot_all_IV(pwd, '_SingleNeuronFitting5_dend', v, ...
                IInitIT6, IInfIT6, IInfIh6, ...
                IInfIKir, IInitIA, IInfIA, IInitINaP, IInfINaP);

% Plot steady state I_V curves only
compute_and_plot_steady_IV(pwd, '_Destexhe_1998', v, IInfIT1, IInfIh1, ...
                IInfIKir, IInfIA, IInfINaP);
compute_and_plot_steady_IV(pwd, '_Destexhe_old', v, IInfIT2, IInfIh1, ...
                IInfIKir, IInfIA, IInfINaP);
compute_and_plot_steady_IV(pwd, '_Christine_soma', v, IInfIT3, IInfIh3, ...
                IInfIKir, IInfIA, IInfINaP);
compute_and_plot_steady_IV(pwd, '_Christine_dend', v, IInfIT4, IInfIh3, ...
                IInfIKir, IInfIA, IInfINaP);
compute_and_plot_steady_IV(pwd, '_SingleNeuronFitting5_soma', v, IInfIT5, IInfIh5, ...
                IInfIKir, IInfIA, IInfINaP);
compute_and_plot_steady_IV(pwd, '_SingleNeuronFitting5_dend', v, IInfIT6, IInfIh6, ...
                IInfIKir, IInfIA, IInfINaP);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function hfig = m3ha_compute_and_plot_all_IV (outFolder, suffix, v, IInitIT, IInfIT, IInfIh, IInfIKir, IInitIA, IInfIA, IInitINaP, IInfINaP)

hfig = figure;
clf(hfig);
hold on;
cm = colormap((jet(5)));
plot(v, IInitIT, '--', 'LineWidth', 2, 'Color', cm(1, :), ...
    'DisplayName', 'I_{T,init}');
plot(v, IInfIT, 'LineWidth', 2, 'Color', cm(1, :), ...
    'DisplayName', 'I_{T,\infty}');
plot(v, IInfIh, 'LineWidth', 2, 'Color', cm(2, :), ...
    'DisplayName', 'I_{h,\infty}');
plot(v, IInfIKir, 'LineWidth', 2, 'Color', cm(3, :), ...
    'DisplayName', 'I_{Kir,\infty}');
plot(v, IInitIA, '--', 'LineWidth', 2, 'Color', cm(4, :), ...
    'DisplayName', 'I_{A,init}');
plot(v, IInfIA, 'LineWidth', 2, 'Color', cm(4, :), ...
    'DisplayName', 'I_{A,\infty}');
plot(v, IInitINaP, '--', 'LineWidth', 2, 'Color', cm(5, :), ...
    'DisplayName', 'I_{NaP,init}');
plot(v, IInfINaP, 'LineWidth', 2, 'Color', cm(5, :), ...
    'DisplayName', 'I_{NaP,\infty}');
xlim([min(v), max(v)]);
xlabel('Membrane potential (mV)');
ylabel('Current (mA/cm^2)');
title('I-V relationships');
legend('location', 'northwest');
set(gca, 'FontSize', 20);
saveas(hfig, fullfile(outFolder, ['I-V_all', suffix]), 'png');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function hfig = compute_and_plot_steady_IV (outFolder, suffix, v, IInfIT, IInfIh, IInfIKir, IInfIA, IInfINaP)

hfig = figure;
clf(hfig);
hold on;
cm = colormap((jet(5)));
plot(v, IInfIT, 'LineWidth', 2, 'Color', cm(1, :), ...
    'DisplayName', 'I_{T,\infty}');
plot(v, IInfIh, 'LineWidth', 2, 'Color', cm(2, :), ...
    'DisplayName', 'I_{h,\infty}');
plot(v, IInfIKir, 'LineWidth', 2, 'Color', cm(3, :), ...
    'DisplayName', 'I_{Kir,\infty}');
plot(v, IInfIA, 'LineWidth', 2, 'Color', cm(4, :), ...
    'DisplayName', 'I_{A,\infty}');
plot(v, IInfINaP, 'LineWidth', 2, 'Color', cm(5, :), ...
    'DisplayName', 'I_{NaP,\infty}');
xlim([min(v), max(v)]);
xlabel('Membrane potential (mV)');
ylabel('Current (mA/cm^2)');
title('I-V relationships');
legend('location', 'southeast');
set(gca, 'FontSize', 20);
saveas(hfig, fullfile(outFolder, ['I-V_steady', suffix]), 'png');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

