%% minEASE_compile.m
%% Compiles minEASE.m and dependent files into a standalone executable
%
% Requires:
% Dependent files in cd/:
%       minEASE.m
%       local.settings              (through minEASE.m)
%       minEASE_combine_events.m         (through minEASE.m)
%       minEASE_compute_plot_average_psc.m  
%                                   (through minEASE_detect_gapfree_events.m)
%       minEASE_detect_gapfree_events.m     (through minEASE.m)
%       minEASE_examine_gapfree_events.m    (through minEASE.m)
%       minEASE_gui_examine_events.m        (through minEASE_examine_gapfree_events.m)
%       minEASE_plot_gapfree_events.m       (through minEASE_detect_gapfree_events.m,
%                                            minEASE_gui_examine_events.m)
%       minEASE_read_params.m               (through minEASE.m)
%
% Dependent files in /home/Matlab/Adams_Functions/:
%       adjust_peaks.m              (through find_directional_events.m,
%                                            minEASE_gui_examine_events.m)
%       all_data_files.m            (through minEASE.m, combine_sweeps.m)
%       check_subdir.m              (through minEASE.m)
%       combine_sweeps.m            (through minEASE.m)
%       compute_average_PSC_trace.m (through minEASE_compute_plot_average_psc.m)
%       compute_rms_Gaussian.m              (through minEASE_detect_gapfree_events.m, 
%                                            minEASE_examine_gapfree_events.m, 
%                                            find_directional_events.m,
%                                            minEASE_gui_examine_events.m)
%       dlmwrite_with_header.m      (through minEASE_examine_gapfree_events.m, 
%                                            minEASE_combine_events.m)
%       find_custom.m               (through find_directional_events.m,
%                                            minEASE_gui_examine_events.m)
%       find_directional_events.m   (through minEASE_detect_gapfree_events.m)
%       find_in_strings.m           (through minEASE_read_params.m)
%       get_idxEnd.m                (through minEASE.m, minEASE_gui_examine_events.m)
%       identify_bursts.m           (through minEASE_detect_gapfree_events.m)
%       identify_channels.m         (through minEASE.m, combine_sweeps.m)
%       increment_editbox.m         (through minEASE_gui_examine_events.m)
%       intersectm.m                (through find_in_strings.m)
%       isfigtype.m                 (through minEASE_detect_gapfree_events.m)
%       istype.m                    (through isfigtype.m)
%       my_closereq.m               (through minEASE_gui_examine_events.m)
%       print_cellstr.m             (through print_or_show_message.m)
%       print_or_show_message.m     (through minEASE.m, minEASE_combine_events.m, 
%                                            minEASE_compute_plot_average_psc.m,
%                                            minEASE_detect_gapfree_events.m
%                                            compute_average_PSC_trace.m, 
%                                            combine_sweeps.m)
%       restore_fields.m            (through minEASE.m)
%       set_fields_zero.m           (through minEASE.m)
%       sigfig.m                    (through minEASE.m)
%       validate_string.m           (through minEASE.m, minEASE_gui_examine_events.m,
%                                            isfigtype.m)
%
% Dependent files in /home/Matlab/Downloaded_Functions/:
%       abf2load.m                  (through minEASE.m, combine_sweeps.m)
%       rgb.m                       (through minEASE_plot_gapfree_events.m,
%                                            minEASE_gui_examine_events.m)

% File History
% 2018-XX-XX Created by Adam Lu
% 2018-02-06 Added print_cellstr.m in the list to compile
% 2018-02-08 Added get_idxEnd.m in the list to compile
% 2018-05-16 Added istype.m in the list to compile

%%
mcc -m -v -I /home/Matlab/minEASE ...
    -a local.settings ...
    -a minEASE_combine_events.m ...
    -a minEASE_compute_plot_average_psc.m ...
    -a minEASE_detect_gapfree_events.m ...
    -a minEASE_examine_gapfree_events.m ...
    -a minEASE_gui_examine_events.m ...
    -a minEASE_plot_gapfree_events.m ...
    -a minEASE_read_params.m ...
    -a /home/Matlab/Adams_Functions/adjust_peaks.m ...
    -a /home/Matlab/Adams_Functions/all_data_files.m ...
    -a /home/Matlab/Adams_Functions/check_subdir.m ...
    -a /home/Matlab/Adams_Functions/combine_sweeps.m ...
    -a /home/Matlab/Adams_Functions/compute_average_PSC_trace.m ...
    -a /home/Matlab/Adams_Functions/compute_rms_Gaussian.m ...
    -a /home/Matlab/Adams_Functions/dlmwrite_with_header.m ...
    -a /home/Matlab/Adams_Functions/find_custom.m ...
    -a /home/Matlab/Adams_Functions/find_directional_events.m ...
    -a /home/Matlab/Adams_Functions/find_in_strings.m ...
    -a /home/Matlab/Adams_Functions/get_idxEnd.m ...
    -a /home/Matlab/Adams_Functions/identify_bursts.m ...
    -a /home/Matlab/Adams_Functions/identify_channels.m ...
    -a /home/Matlab/Adams_Functions/increment_editbox.m ...
    -a /home/Matlab/Adams_Functions/intersectm.m ...
    -a /home/Matlab/Adams_Functions/isfigtype.m ...
    -a /home/Matlab/Adams_Functions/istype.m ...
    -a /home/Matlab/Adams_Functions/my_closereq.m ...
    -a /home/Matlab/Adams_Functions/print_cellstr.m ...
    -a /home/Matlab/Adams_Functions/print_or_show_message.m ...
    -a /home/Matlab/Adams_Functions/restore_fields.m ...
    -a /home/Matlab/Adams_Functions/set_fields_zero.m ...
    -a /home/Matlab/Adams_Functions/sigfig.m ...
    -a /home/Matlab/Adams_Functions/validate_string.m ...
    -a /home/Matlab/Downloaded_Functions/abf2load.m ...
    -a /home/Matlab/Downloaded_Functions/rgb.m ...
    minEASE;


